# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_PRIORITY_meta-bearcreektech = "10"

BBFILE_COLLECTIONS += "meta-bearcreektech"
BBFILE_PATTERN_meta-bearcreektech = "^${LAYERDIR}/"

LAYERSERIES_COMPAT_meta-bearcreektech = "scarthgap"